const IssueDetailAction = {};

// Not promise
IssueDetailAction.SET_LABEL_LIST = 'SET_LABEL_LIST';
IssueDetailAction.SET_ASSIGNEE_LIST = 'SET_ASSIGNEE_LIST';
IssueDetailAction.SET_MILESTONE = 'SET_MILESTONE';
IssueDetailAction.SET_ISSUE_TITLE = 'SET_ISSUE_TITLE';
IssueDetailAction.SET_ISSUE_CONTENT = 'SET_ISSUE_CONTENT';
IssueDetailAction.SET_COMMENT_CONTENT = 'SET_COMMENT_CONTENT';
IssueDetailAction.ADD_COMMENT = 'ADD_COMMENT';
IssueDetailAction.SET_ISSUE_STATE = 'SET_ISSUE_STATE';

// Promise
IssueDetailAction.UPDATE_MILESTONE = 'UPDATE_MILESTONE';
IssueDetailAction.UPDATE_LABEL_LIST = 'UPDATE_LABEL_LIST';
IssueDetailAction.UPDATE_ASSIGNEE_LIST = 'UPDATE_ASSIGNEE_LIST';
IssueDetailAction.UPDATE_ISSUE_TITLE = 'UPDATE_ISSUE_TITLE';
IssueDetailAction.UPDATE_ISSUE_CONTENT = 'UDPATE_ISSUE_CONTENT';
IssueDetailAction.UPDATE_COMMENT_CONTENT = 'UPDATE_COMMENT_CONTENT';
IssueDetailAction.CREATE_COMMENT = 'CREATE_COMMENT';
IssueDetailAction.CHANGE_ISSUE_STATE = 'CHANGE_ISSUE_STATE';

export default IssueDetailAction;
